<?php

namespace app\models;

use yii\base\Model;
use yii\data\ActiveDataProvider;

class CarpoolingTripSearch extends CarpoolingTrip
{


    public function rules()
    {
        return [
//            [['date', 'type_id'], 'required'],
            [['type_id', 'places'], 'integer'],
            [['date'], 'safe'],

        ];
    }

    public function scenarios()
    {
        return Model::scenarios(); // TODO: Change the autogenerated stub
    }

    public function search($params)
    {
        $query = CarpoolingTrip::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()) {
            return $dataProvider;
        }

        $query->andFilterWhere([
            'type_id' => $this->type_id,
            'places' => $this->places,
            'date' => $this->date,

        ]);

        return $dataProvider;

    }


}